//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carnotaurus.GhostPubsMvc.Web
{
    using System;
    using System.Collections.Generic;

    public interface IName
    {
        String Name { get; set; }
    }

    public interface IOrgModel
    {
        String JumboTitle { get; set; }

        String Action { get; set; }
    }

    //public partial class Region : IName
    //{
    //    public string Name
    //    {
    //        get
    //        {
    //            return this.Description;
    //        }
    //        set
    //        {
    //            this.Description = value;
    //        }
    //    }
    //}
}