namespace Carnotaurus.GhostPubsMvc.Common.Bespoke.Enumerations
{
    public enum PageTypeEnum
    {
        Country,
        Region,
        County,
        Locality,
        Pub,
        Sitemap,
        Submissions,
        Promotions,
        Competitions,
        Partnerships,
        Partners,
        FeaturedPartner,
        Contributors,
        About,
        Home,
        Newsletter,
        Accessibility,
        Terms,
        ContactUs,
        Privacy,
        FaqBrewery,
        FaqPub,
        FaqParanormalServiceConsumers,
        FaqParanormalServiceProviders,
        Missing,
    }
}